version: '3.4'
services:
  app:
    image: treatfield-api
    container_name: treatfield-api
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - "./:/go/src/treatfield-api"
    networks:
      - treatfield_default

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    env_file:
      - 'config/env.influxdb'
    volumes:
      - ~/docker/influxdb/data:/var/lib/influxdb
      #- ./:/etc/influxdb/influxdb.conf
    networks:
      - treatfield_default

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - treatfield_default

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'config/env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      - ~/docker/grafana/data:/var/lib/grafana
    networks:
      - treatfield_default

networks:
  treatfield_default:
    external: true
