version: '3.3'
services:
  app:
    container_name: treatfield-api
    image: treatfield-api
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - "./:/go/src/treatfield-api"
    networks:
      - treatfield_default

networks:
  treatfield_default:
    external: true
